export enum ErrorCode {
    VALIDATION_ERROR = 'VALIDATION_ERROR',
    TIMEOUT_ERROR = 'TIMEOUT_ERROR',
    RATE_LIMIT_ERROR = 'RATE_LIMIT_ERROR',
    PLATFORM_ERROR = 'PLATFORM_ERROR',
    AUTH_ERROR = 'AUTH_ERROR',
    INTERNAL_ERROR = 'INTERNAL_ERROR',
}
